version: '3.9'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
        MYSQL_DATABASE: 'library'
        MYSQL_USER: 'user1'
        MYSQL_PASSWORD: '####'
        MYSQL_ROOT_PASSWORD: '####'
        MYSQL_HOST:
    volumes:
      - ./db:/var/lib/mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3302:3306"
    expose:
      # Opens port 3306 on the container
      - '3302'
      # Where our data will be persisted
    networks:
      -  default

  library:
    build:
      context: ./library
      dockerfile: Dockerfile
    container_name: library
    volumes:
      - ./library:/app
    ports:
      - '8000:8000'
    depends_on:
      - mysql
      - redis
      - celery
    networks:
      -  default


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      -  default

  celery:
    build:
      context: ./library
      dockerfile: Dockerfile-celery
    container_name: celery
    command: celery -A library worker -l info --pool=solo
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ./library:/app
    depends_on:
      - redis
      - mysql
    networks:
      -  default

networks:
  default:
    driver: bridge